### ISSUE TITLE
Is "pip install -e pde-superresolution" the right command?

### ISSUE THREAD

**Issue by lucianodrozda** [google/data-driven-discretization-1d#9]
Hi, I'd like to point out that the instruction _pip install_ related to the project might not be right one. Instead, one should type

_pip install -e data-driven-discretization-1d_

as it searches the **setup.py** file inside this folder. Am I wrong? At least this was the only way I succeeded installing the package...

**Comment by yohai** [comment]
In the [installation section of the README file](https://github.com/google/data-driven-discretization-1d#local-installation) we have the -e flag. Where did you see a `pip install` command without it?

**Comment by shoyer** [comment]
Thanks for pointing this out. Indeed, you are correct: it should be `pip install -e data-driven-discretization-1d` (which is what we have in our notebooks), not `pip install -e pde-superresolution`. I fixed this in the README.
